eunoiaproject/coreapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'coreapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),

    # Brainstorm
    path('home/brainstorm/<action>/<int:id>',views.brainstorm, name='brainstorm'),
    # Ideas
    path('home/idea/<action>/<int:id>',views.idea, name='idea'),

    # kanban
    path('home/kanban/<action>/<int:id>',views.kanban, name='kanban'),

    # Product
    path('home/product/<int:product_id>/<submenu>',login_required(views.ProductView.as_view()), name='product'),
    # path('home/product/<int:product_id>/<submenu>/<action>/<int:id>',views.product, name='product'),
  
    # path('home/product_admin',views.product_admin, name='product_admin')

    path('notify/',views.notify, name='notify'),
    path('signup/', views.signup, name='signup'),

    path('signup/account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

eunoiaproject/eunoiaapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'eunoiaapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),

    # Brainstorm
    path('home/brainstorm/<action>/<int:id>',views.brainstorm, name='brainstorm'),
    # Ideas
    path('home/idea/<action>/<int:id>',views.idea, name='idea'),

    # kanban
    path('home/kanban/<action>/<int:id>',views.kanban, name='kanban'),

    # Product
    path('home/product/<int:product_id>/<submenu>',login_required(views.ProductView.as_view()), name='product'),
    # path('home/product/<int:product_id>/<submenu>/<action>/<int:id>',views.product, name='product'),
  
    # path('home/product_admin',views.product_admin, name='product_admin')

    path('notify/',views.notify, name='notify'),
    path('signup/', views.signup, name='signup'),

    path('signup/account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

eunoiaproject/eunoiaproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eunoiaapp.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

eunoiaproject/eunoiaapp/views.py
import datetime
from random import randint 
import json

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.template.loader import render_to_string


from django.contrib.auth.models import User

from .tokens import account_activation_token
from .models import Profile
from .forms import SignUpForm


from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.db.models import Q

from django.db.models.functions import TruncMonth
from django.db.models.functions import ExtractMonth
from django.db.models import Avg, Count, Min, Sum

# from .models import
from .tokens import account_activation_token
from .models import Profile, Idea, Product, Feature, FeatureSequence, Activity, BrainStorm, IdeaNote,IdeaNoteAction,ActivitySequence
from .forms import IdeaForm, MyRadioForm, FeatureForm, ActivityForm, BrainStormForm, ShortActivityForm,OpportunityForm


def index(request):
    num =   randint(0,15)
    context = {'chaos_num':num}

    return render(request, "eunoiaapp/index.html", context)

@login_required
def home(request):
    # print(request.headers)
    global_context = get_global_menu_context(request.user)
    print(global_context)
    context = {
        'global_context' : global_context
    }
    return render(request, "eunoiaapp/home.html", context)


@login_required
def kanban(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "action" : action,
        "idea_id" : id,
        'global_context' : global_context
    }
    if action == 'all' and request.method == 'GET':
        context['ideas'] = Idea.objects.filter(created_by=global_context['profile_instance'])

    elif action == 'idea_kanban' and request.method == 'GET':
        context['idea'] = Idea.objects.get(pk=id)
        context['todos'] = Activity.objects.filter(related_to_idea=id,status='TODO',created_by=global_context['profile_instance'])
        context['inprogress'] = Activity.objects.filter(related_to_idea=id,status='IN_PROGRESS',created_by=global_context['profile_instance'])
        context['done'] = Activity.objects.filter(related_to_idea=id,status='DONE',created_by=global_context['profile_instance'])

        context['todo_seq'] = ActivitySequence.objects.filter(type='TODO').order_by('order')
        context['inprogress_seq'] = ActivitySequence.objects.filter(type='IN_PROGRESS').order_by('order')
        context['done_seq'] = ActivitySequence.objects.filter(type='DONE').order_by('order')

    elif action == 'idea_add_todo' and request.method == 'GET':
        context['todo_form'] = ShortActivityForm()

    elif action == 'idea_add_todo' and request.method == 'POST':
        form = ShortActivityForm(request.POST)
        if form.is_valid():
            activity_instance = form.save(commit=False)
            activity_instance.created_by = global_context['profile_instance']
            activity_instance.status = 'TODO'
            activity_instance.complexity = 'UNKNOWN'
            activity_instance.related_to_idea = Idea.objects.get(pk=id)
            activity_instance.save()
            print(activity_instance.id)
            ActivitySequence.objects.create(activity_id = activity_instance.id,order=activity_instance.id, type='TODO')
        return redirect('/home/kanban/idea_kanban/{}'.format(id))

  
    elif action == 'edit_activity' and request.method == 'GET':
        context['todo_form'] = ShortActivityForm()
        activity = Activity.objects.get(pk=id)
        id = activity.related_to_idea.id
        context['idea_id'] = id

    elif action == 'edit_activity' and request.method == 'POST':
        pass

    elif action == 'reorder_activity' and request.method == 'POST':
        orders = json.loads(request.POST['order'])
        print(orders)
        for activity_type in orders:
            for activity_arr in activity_type:
                print(activity_arr)

                ActivitySequence.objects.filter(activity_id = activity_arr[0]).update(order=activity_arr[1],type=activity_arr[2])
                activity = Activity.objects.get(pk = activity_arr[0])
                activity.status=activity_arr[2]
                activity.save()
  
    return render(request, "eunoiaapp/kanban.html", context)

@login_required
def idea(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "username": request.user,
        "action" : action,
        "idea_id" : id,
        "radio_form" : MyRadioForm(),
        "global_context" : global_context
    }
    if action == 'all':
        context['ideas'] = Idea.objects.filter(created_by=global_context['profile_instance'])
    elif action == 'new_idea' and request.method == 'POST':
        form = IdeaForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            idea_instance = form.save(commit=False)
            idea_instance.created_by = global_context['profile_instance']
            idea_instance.save()
            return redirect('/home/idea/all/0')
    elif action == 'new_ideafrombrainstorming' and request.method == 'POST':
        form = IdeaForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            idea_instance = form.save(commit=False)
            idea_instance.created_by = global_context['profile_instance']
            idea_instance.brainstorming = BrainStorm.objects.get(pk=id)
            idea_instance.save()
            return redirect('/home/idea/all/0')
    elif action == 'new_idea' and request.method == 'GET' and id <= 0:
        # In case of new
        context['form'] = IdeaForm()     
    # In case of edit
    elif action == 'existing_idea' and request.method == 'GET' and id > 0:
        idea = Idea.objects.get(pk=id)
        context['idea_instance'] = idea
        context['form'] = IdeaForm(instance=idea)
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=idea.brainstorming,created_by=global_context['profile_instance'])
    elif action == 'new_ideafrombrainstorming' and request.method == 'GET' and id >0:
        context['form'] = IdeaForm()    
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance'])
    elif action == 'existing_idea' and request.method == 'POST' and id > 0:
        idea_instance = Idea.objects.get(pk=id)      
        form = IdeaForm(request.POST, instance=idea_instance)
        if form.is_valid():            
            form.save()
            # if productize, create a product out of it
            idea = Idea.objects.get(pk=id)
            if idea.is_productized():
                product = Product(idea = idea, name = idea.idea_name, owner = global_context['profile_instance'] )   
                product.save()       
            return redirect('/home/idea/all/0')
    


  
    return render(request, "eunoiaapp/idea.html", context)


@login_required
def brainstorm(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "action" : action,
        "idea_id" : id,
        "global_context" : global_context
    }
    if action == 'all':
        context['brainstorms'] = BrainStorm.objects.filter(created_by=global_context['profile_instance'])
    elif action == 'new_brainstorm' and request.method == 'POST':
        form = BrainStormForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            brainstorm_instance = form.save(commit=False)
            brainstorm_instance.created_by = global_context['profile_instance']
            brainstorm_instance.save()
            return redirect('/home/brainstorm/all/0')
    elif action == 'new_brainstorm' and request.method == 'GET' and id <= 0:
        # In case of new
        context['form'] = BrainStormForm()     
    # In case of edit
    elif action == 'ideanote' and request.method == 'GET' and id > 0:
        context['brainstorm'] = BrainStorm.objects.get(pk=id)
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance']).exclude(title__exact='',description__exact='').select_related()
    elif action == 'new_ideanote' and request.method == 'GET' and id > 0:
        brainstorm = BrainStorm.objects.get(pk=id)
        context['brainstorm'] = brainstorm  
        blank_ideanote = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance'],title__exact='',description__exact='')
        ideanote = None
        if blank_ideanote.count() == 0:
            ideanote = IdeaNote.objects.create(belongs_to_brainstorm=brainstorm,created_by=global_context['profile_instance'],title='',description='')
        else:
            ideanote = blank_ideanote[0]
        print('********',ideanote)
        context['new_ideanote'] = ideanote
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance']).exclude(title__exact='',description__exact='')
    elif action == 'update_ideanote' and request.method == 'POST':
       
        title = request.POST['title'] if 'title' in request.POST else ''
        description = request.POST['cnt'] if 'cnt' in request.POST else ''
     
        ideanote = IdeaNote.objects.get(pk=id)
        if len(title.strip()) == 0 and len(description.strip()) == 0:
            print('Nothing to update')
            return HttpResponse()
        elif title and len(title.strip())>0:

eunoiaproject/eunoiaapp/templates/eunoiaapp/product/activityform.html
{% for error in form.non_field_errors %}
<div class="form-group has-errors text-danger small">
    {{error}}
</div>
{% endfor %}
{% for field in form %}
    {% if field.field.widget.attrs.input_type == 'text' %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                    class="required">*</span>{% endif %}</label>
        </div>
        <div class="col-9 col-sm-12">
            {{ field }}
            {% if field.help_text %}
            <p class="form-input-hint">{{ field.errors|safe }}</p>
            {% endif %}
            {% if field.errors %} <p class="form-input-hint">{{field.errors.0}}</p>{% endif %}
        </div>
    </div>
    {% elif field.field.widget.attrs.input_type == 'checkbox' %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                    class="required">*</span>{% endif %}</label>
        </div>
        <div class="col-9 col-sm-12">
            <label class="form-checkbox form-inline">
                {{field}}<i class="form-icon"></i>
                {% if field.errors %} <p class="form-input-hint">{{field.errors.0}}</p>{% endif %}
            </label>

        </div>

        <div class="col-9 col-sm-12">
            {% if field.help_text %}
            <p class="form-input-hint">{{ field.errors|safe }}</p>
            {% endif %}
        </div>
    </div>

    {% elif field.field.widget.attrs.input_type == 'textarea' %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
        </div>
        <div class="col-9 col-sm-12">
            {{ field }}
            {% if field.errors %} <p class="form-input-hint">{{field.errors.0}}</p>{% endif %}
           
        </div>
    </div>


    {% elif field.field.widget.attrs.input_type == 'radio' and field.label == 'Complexity' %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                    class="required">*</span>{% endif %}</label>
        </div>

        <div class="col-9 col-sm-12">
            <!-- For Activity -->
            {% for choice in form.complexity %}
            <label class="form-radio form-inline">
                {{choice.tag}} <i class="form-icon"></i>{{ choice.choice_label }}
            </label>
            {% endfor %}
            {% if field.errors %} <p class="form-input-hint">{{field.errors.0}}</p>{% endif %}


        </div>

    </div>

         {% elif field.field.widget.attrs.input_type == 'radio' %}
        
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                    class="required">*</span>{% endif %}</label>
        </div>

        <div class="col-9 col-sm-12">
          

            {% for choice in form.type %}
            <label class="form-radio form-inline">
                {{choice.tag}} <i class="form-icon"></i>{{ choice.choice_label }}
            </label>

            {% endfor %}
            {% if field.errors %} <p class="form-input-hint">{{field.errors.0}}</p>{% endif %}
        </div>


    </div>
    {% endif %}

{% endfor %}
<div class="form-group">
    <div class="col-11 col-sm-10">
    </div>
    <div class="col-1 col-sm-1">
        <button type="submit" class="btn btn-success input-group-btn">Ok</button>
    </div>
</div>

eunoiaproject/eunoiaapp/templates/eunoiaapp/product/feature.html
{% extends 'eunoiaapp/base.html' %}
{% block content %}
{% load static %}
<div class="container" id="getting-started">
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'eunoiaapp:home'%}">Home</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}">Features</a>
    </li>
    <li class="breadcrumb-item">
      <a class="" href="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}?action=new_feature">+</a>
    </li>
  </ul>


  <!-- Show New Feature Form -->


  {% if action == 'new_feature' or action == 'existing_feature'   %}
  <div class="container">
    <form method="POST" class="form-horizontal"
      action="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}?action={{action|urlencode}}&feature_id={{feature_id|urlencode}}">
      {% csrf_token %}
      {% include 'eunoiaapp/product/featureform.html' %}
    </form>
  </div>
  <!-- Show activities only for existing feature, new features don't have activities -->
  {% if action == 'existing_feature'   %}
  <h4>Activities <a class=""
      href="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu%}?action=new_activity&feature_id={{feature_id|urlencode}} ">+</a>
  </h4>




  <div class="column col-12">
    <div class="filter">
      <input class="filter-tag" id="tag-0" type="radio" name="filter-radio" hidden="" checked="">
      <input class="filter-tag" id="tag-1" type="radio" name="filter-radio" hidden="">
      <input class="filter-tag" id="tag-2" type="radio" name="filter-radio" hidden="">
      <input class="filter-tag" id="tag-3" type="radio" name="filter-radio" hidden="">
      <input class="filter-tag" id="tag-4" type="radio" name="filter-radio" hidden="">
      <input class="filter-tag" id="tag-5" type="radio" name="filter-radio" hidden="">
      <div class="filter-nav">
        <label class="chip" for="tag-0">All</label>
        <label class="chip" for="tag-1" style="background-color:rgb(190, 248, 216)">High</label>
        <label class="chip" for="tag-2" style="background-color:rgb(200, 203, 248)">Medium</label>
        <label class="chip" for="tag-3" style="background-color:rgb(246, 250, 193)">Low</label>
        <label class="chip" for="tag-4" style="background-color:rgb(244, 214, 248)">Very Low</label>
        <label class="chip" for="tag-5" style="background-color:rgb(244, 214, 248)">Unknown</label>

      </div>


      <div class="filter-body columns" id="sortable-activities" class="container">


        {% for seq in activities_seq %}
        {% for activity in activities %}
        {% if seq.type == 'TODO' and seq.activity_id == activity.id %}



        <div id="activity-id-{{activity.id}}" class="column col-12 filter-item"
          data-tag="{% if activity.complexity == 'HIGH'%}tag-1{% elif activity.complexity == 'MEDIUM'%}tag-2{% elif activity.complexity == 'LOW'%}tag-3{% elif activity.complexity == 'VERY_LOW'%}tag-4{% elif activity.complexity == 'UNKNOWN'%}tag-5{% endif %}">
          <div class=" card">
            <div class="card-header">
              <div class="card-title text-bold">{{activity.outcome}} <a
                  href="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}?action=existing_activity&activity_id={{activity.id}}"
                  class="default btn float-right"><i class="icon icon-edit"></i></a></div>
              <div class="card-subtitle">{{activity.description}}</div>
            </div>
          </div>
        </div>
        {%endif%}
        {%endfor%}
        {%endfor%}

      </div>
    </div>
  </div>
  {% endif %}

  {% elif action == 'new_activity'  %}
  <H4>Activity</H4>
  <h6>Ability: {{feature.ability_to}} <em> for </em> {{feature.ability_for}}</h6>
  <h6>Description: {{feature.description}}</h6>
  <div class="container">
    <form method="POST" class="form-horizontal"
      action="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}?action={{action|urlencode}}&feature_id={{feature_id|urlencode}}">
      {% csrf_token %}
      {% include 'eunoiaapp/product/activityform.html' %}
    </form>
  </div>

  {% elif action == 'existing_activity'  %}
  <H4>Feature</H4>
  <h6>Ability: {{feature.ability_for}}</h6>
  <h6>Description: {{feature.description}}</h6>
  <div class="container">
    <form method="POST" class="form-horizontal"
      action="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}?action={{action|urlencode}}&activity_id={{activity_id|urlencode}}">
      {% csrf_token %}
      {% include 'eunoiaapp/product/activityform.html' %}
    </form>
  </div>
  {% endif %}

  {% if features %}
  <div class="column col-12">
    <div class="filter">
      <input class="filter-tag" id="tag-0" type="radio" name="filter-radio" hidden="" checked="">
      <input class="filter-tag" id="tag-1" type="radio" name="filter-radio" hidden="">
      <input class="filter-tag" id="tag-2" type="radio" name="filter-radio" hidden="">
      <input class="filter-tag" id="tag-3" type="radio" name="filter-radio" hidden="">
      <input class="filter-tag" id="tag-4" type="radio" name="filter-radio" hidden="">
      <div class="filter-nav">
        <label class="chip" for="tag-0">All</label>

        <label class="chip" for="tag-1" style="background-color:rgb(190, 248, 216)">Must Have</label>
        <label class="chip" for="tag-2" style="background-color:rgb(200, 203, 248)">Should Have</label>
        <label class="chip" for="tag-3" style="background-color:rgb(246, 250, 193)">Could Have</label>
        <label class="chip" for="tag-4" style="background-color:rgb(244, 214, 248)">Good to Have</label>

      </div>


      <div class="filter-body columns" id="sortable" class="container">
        {% for feature_seq in features_sequence %}
        {% for feature in features %}
        {% if feature.id == feature_seq.feature_id %}
        <div id="feature-id-{{feature.id}}" class="column col-12 filter-item"
          data-tag="{% if feature.priority == 'MUST_HAVE'%}tag-1{% elif feature.priority == 'SHOULD_HAVE'%}tag-2{% elif feature.priority == 'COULD_HAVE'%}tag-3{% elif feature.priority == 'GOOD_TO_HAVE'%}tag-4{% endif %}">
          <div class="card">
            <div class="card-header">
              <div class="card-title text-bold">Ability to <u>{{feature.ability_to}}</u>, for
                <u>{{feature.ability_for}}</u>
                <a href="{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}?action=existing_feature&feature_id={{feature.id}}"
                  class="default btn float-right"><i class="icon icon-edit"></i></a>
              </div>
              <div class="card-subtitle">{{feature.description}}</div>

            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endfor %}

      </div>
    </div>
  </div>
  {% endif %}

</div>




<script>

  $(document).ready(function () {
    initDragulaForFeatures();
    initDragulaForActivities();
  });
  function initDragulaForFeatures() {

    var drake = dragula([document.getElementById('sortable')], {
      revertOnSpill: true
    });
    drake.on('drop', function (el) {
      $(el).fadeOut(100).css('background-color', 'yellow').fadeIn(100).fadeOut(100).fadeIn(100).css('background-color', 'lightyellow');
      // console.log($(drake.containers[0]).children());
      var order = -1;
      var orderArr = [];
      $(drake.containers[0]).children().each(function (e) {
        var id_str = $(this).attr('id').split('feature-id-')[1];
        var id = parseInt(id_str);
        order = order + 1
        orderArr.push([id, order])
      });

      console.log(orderArr);

      // send ajax request

      $.ajax({
        url: "{% url 'eunoiaapp:product' product_id=product_id submenu=submenu %}?action=reorder_feature",
        method: 'POST',
        data: { order: JSON.stringify(orderArr) },
        success: function (result) {

        }

      });
    });
  }


  // Drag for activities


  function initDragulaForActivities() {

    var drake = dragula([document.getElementById('sortable-activities')], {
      revertOnSpill: true
    });


    drake.on('drop', function (el) {
      $(el).fadeOut(100).css('background-color', 'yellow').fadeIn(100).fadeOut(100).fadeIn(100).css('background-color', 'lightyellow');
      // console.log($(drake.containers[0]).children());
      var order = -1;
      var orderArr = [];
      var allOrderArr = [];
      $(drake.containers[0]).children().each(function (e) {
        var id_str = $(this).attr('id').split('activity-id-')[1];
        var id = parseInt(id_str);
        order = order + 1
        orderArr.push([id, order, 'TODO'])
      });

      console.log(orderArr);
      console.log(orderArr);
      allOrderArr.push(orderArr);
      // send ajax request
      //{% url 'eunoiaapp:kanban' action='reorder_activity' id=idea_id 
      $.ajax({
        url: "{% url 'eunoiaapp:kanban' action='reorder_activity' id=0 %}",
        method: 'POST',
        data: { order: JSON.stringify(allOrderArr) },
        success: function (result) {

        }

      });
    });



  }
</script>

{% endblock %}

eunoiaproject/eunoiaapp/templates/eunoiaapp/product/task.html
sfsdf<div class="modal active" id="task-modal">
  <a class="modal-overlay" href="#" aria-label="Close"></a>
  <div class="modal-container" role="document">
    <div class="modal-header"><a class="btn btn-clear float-right" href="#" aria-label="Close"
        onclick="closeTaskModel();"></a>
      <div class="modal-title h5">{{activity.outcome}}</div>
    </div>


    <div class="modal-body">
      <div class="content">
        <form method="POST"
          actino="{% url 'eunoiaapp:product' product_id=product.id submenu='activitykanban'%}?action=feature_update_todo&feature_id={{feature_id}}&activity_id={{activity.id}}">
          {{activity.id}}
          {% csrf_token %}
          {% include 'eunoiaapp/product/taskform.html'%}
          <button type="submit" class="btn btn-success input-group-btn">Ok</button>
        </form>


        <!-- <table class="table">
          <thead>
              <tr>
                  <th>Title</th>
                  <th>Author</th>
                  <th>Created</th>
                  <th>Status</th>
              </tr>
          </thead>
          <tbody>
            {% for activity in activities %}
              <tr class="active">
                  <td>
                      <div class="popover popover-right">
  
                          <span><a href="{% url 'eunoiaapp:product' product_id=product.id submenu='kanban'%}?action=feature_update_todo&feature_id={{feature.id}}&activity_id={{activity.id}}">{{activity.id}}</a></span>
                          <div class="popover-container">
                              <div class="card">
                                  <div class="card-body">
                                      {{activity.outcome}}
                                  </div>
                              </div>
  
                          </div>
                      </div>
                  </td>
  
  
                  <td> {{activity.created_by}}</td>
                  <td>{{activity.created_on}}</td>
                  <td>{{activity.status}}</td>
              </tr>
              {% endfor %}
          </tbody>
      </table> -->
     
       
     
      </div>


    </div>
    <div class="modal-footer">
      <!-- <a class="btn btn-link" onclick="closeTaskModel();" href="#">Close</a> -->

    </div>

  </div>
</div>

<script>
  function closeTaskModel() {
    $("div#task-modal").removeClass("active");
  }
</script>