eunoiaproject/coreapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'coreapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),

    # Brainstorm
    path('home/brainstorm/<action>/<int:id>',views.brainstorm, name='brainstorm'),
    # Ideas
    path('home/idea/<action>/<int:id>',views.idea, name='idea'),

    # kanban
    path('home/kanban/<action>/<int:id>',views.kanban, name='kanban'),

    # Product
    path('home/product/<int:product_id>/<submenu>',login_required(views.ProductView.as_view()), name='product'),
    # path('home/product/<int:product_id>/<submenu>/<action>/<int:id>',views.product, name='product'),
  
    # path('home/product_admin',views.product_admin, name='product_admin')

    path('notify/',views.notify, name='notify'),
    path('signup/', views.signup, name='signup'),

    path('signup/account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

eunoiaproject/eunoiaapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'eunoiaapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),

    # Brainstorm
    path('home/brainstorm/<action>/<int:id>',views.brainstorm, name='brainstorm'),
    # Ideas
    path('home/idea/<action>/<int:id>',views.idea, name='idea'),

    # kanban
    path('home/kanban/<action>/<int:id>',views.kanban, name='kanban'),

    # Product
    path('home/product/<int:product_id>/<submenu>',login_required(views.ProductView.as_view()), name='product'),
    # path('home/product/<int:product_id>/<submenu>/<action>/<int:id>',views.product, name='product'),
  
    # path('home/product_admin',views.product_admin, name='product_admin')

    path('notify/',views.notify, name='notify'),
    path('signup/', views.signup, name='signup'),

    path('signup/account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

eunoiaproject/eunoiaproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eunoiaapp.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

eunoiaproject/eunoiaapp/views.py
import datetime
from random import randint 
import json

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.template.loader import render_to_string


from django.contrib.auth.models import User

from .tokens import account_activation_token
from .models import Profile
from .forms import SignUpForm


from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.db.models import Q

from django.db.models.functions import TruncMonth
from django.db.models.functions import ExtractMonth
from django.db.models import Avg, Count, Min, Sum

# from .models import
from .tokens import account_activation_token
from .models import Profile, Idea, Product, Feature, FeatureSequence, Activity, BrainStorm, IdeaNote,IdeaNoteAction,ActivitySequence
from .forms import IdeaForm, MyRadioForm, FeatureForm, ActivityForm, BrainStormForm, ShortActivityForm,OpportunityForm


def index(request):
    num =   randint(0,15)
    context = {'chaos_num':num}

    return render(request, "eunoiaapp/index.html", context)

@login_required
def home(request):
    # print(request.headers)
    global_context = get_global_menu_context(request.user)
    print(global_context)
    context = {
        'global_context' : global_context
    }
    return render(request, "eunoiaapp/home.html", context)


@login_required
def kanban(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "action" : action,
        "idea_id" : id,
        'global_context' : global_context
    }
    if action == 'all' and request.method == 'GET':
        context['ideas'] = Idea.objects.filter(created_by=global_context['profile_instance'])

    elif action == 'idea_kanban' and request.method == 'GET':
        context['idea'] = Idea.objects.get(pk=id)
        context['todos'] = Activity.objects.filter(related_to_idea=id,status='TODO',created_by=global_context['profile_instance'])
        context['inprogress'] = Activity.objects.filter(related_to_idea=id,status='IN_PROGRESS',created_by=global_context['profile_instance'])
        context['done'] = Activity.objects.filter(related_to_idea=id,status='DONE',created_by=global_context['profile_instance'])

        context['todo_seq'] = ActivitySequence.objects.filter(type='TODO').order_by('order')
        context['inprogress_seq'] = ActivitySequence.objects.filter(type='IN_PROGRESS').order_by('order')
        context['done_seq'] = ActivitySequence.objects.filter(type='DONE').order_by('order')

    elif action == 'idea_add_todo' and request.method == 'GET':
        context['todo_form'] = ShortActivityForm()

    elif action == 'idea_add_todo' and request.method == 'POST':
        form = ShortActivityForm(request.POST)
        if form.is_valid():
            activity_instance = form.save(commit=False)
            activity_instance.created_by = global_context['profile_instance']
            activity_instance.status = 'TODO'
            activity_instance.complexity = 'UNKNOWN'
            activity_instance.related_to_idea = Idea.objects.get(pk=id)
            activity_instance.save()
            print(activity_instance.id)
            ActivitySequence.objects.create(activity_id = activity_instance.id,order=activity_instance.id, type='TODO')
        return redirect('/home/kanban/idea_kanban/{}'.format(id))

  
    elif action == 'edit_activity' and request.method == 'GET':
        context['todo_form'] = ShortActivityForm()
        activity = Activity.objects.get(pk=id)
        id = activity.related_to_idea.id
        context['idea_id'] = id

    elif action == 'edit_activity' and request.method == 'POST':
        pass

    elif action == 'reorder_activity' and request.method == 'POST':
        orders = json.loads(request.POST['order'])
        print(orders)
        for activity_type in orders:
            for activity_arr in activity_type:
                print(activity_arr)

                ActivitySequence.objects.filter(activity_id = activity_arr[0]).update(order=activity_arr[1],type=activity_arr[2])
                activity = Activity.objects.get(pk = activity_arr[0])
                activity.status=activity_arr[2]
                activity.save()
  
    return render(request, "eunoiaapp/kanban.html", context)

@login_required
def idea(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "username": request.user,
        "action" : action,
        "idea_id" : id,
        "radio_form" : MyRadioForm(),
        "global_context" : global_context
    }
    if action == 'all':
        context['ideas'] = Idea.objects.filter(created_by=global_context['profile_instance'])
    elif action == 'new_idea' and request.method == 'POST':
        form = IdeaForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            idea_instance = form.save(commit=False)
            idea_instance.created_by = global_context['profile_instance']
            idea_instance.save()
            return redirect('/home/idea/all/0')
    elif action == 'new_ideafrombrainstorming' and request.method == 'POST':
        form = IdeaForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            idea_instance = form.save(commit=False)
            idea_instance.created_by = global_context['profile_instance']
            idea_instance.brainstorming = BrainStorm.objects.get(pk=id)
            idea_instance.save()
            return redirect('/home/idea/all/0')
    elif action == 'new_idea' and request.method == 'GET' and id <= 0:
        # In case of new
        context['form'] = IdeaForm()     
    # In case of edit
    elif action == 'existing_idea' and request.method == 'GET' and id > 0:
        idea = Idea.objects.get(pk=id)
        context['idea_instance'] = idea
        context['form'] = IdeaForm(instance=idea)
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=idea.brainstorming,created_by=global_context['profile_instance'])
    elif action == 'new_ideafrombrainstorming' and request.method == 'GET' and id >0:
        context['form'] = IdeaForm()    
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance'])
    elif action == 'existing_idea' and request.method == 'POST' and id > 0:
        idea_instance = Idea.objects.get(pk=id)      
        form = IdeaForm(request.POST, instance=idea_instance)
        if form.is_valid():            
            form.save()
            # if productize, create a product out of it
            idea = Idea.objects.get(pk=id)
            if idea.is_productized():
                product = Product(idea = idea, name = idea.idea_name, owner = global_context['profile_instance'] )   
                product.save()       
            return redirect('/home/idea/all/0')
    


  
    return render(request, "eunoiaapp/idea.html", context)


@login_required
def brainstorm(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "action" : action,
        "idea_id" : id,
        "global_context" : global_context
    }
    if action == 'all':
        context['brainstorms'] = BrainStorm.objects.filter(created_by=global_context['profile_instance'])
    elif action == 'new_brainstorm' and request.method == 'POST':
        form = BrainStormForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            brainstorm_instance = form.save(commit=False)
            brainstorm_instance.created_by = global_context['profile_instance']
            brainstorm_instance.save()
            return redirect('/home/brainstorm/all/0')
    elif action == 'new_brainstorm' and request.method == 'GET' and id <= 0:
        # In case of new
        context['form'] = BrainStormForm()     
    # In case of edit
    elif action == 'ideanote' and request.method == 'GET' and id > 0:
        context['brainstorm'] = BrainStorm.objects.get(pk=id)
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance']).exclude(title__exact='',description__exact='').select_related()
    elif action == 'new_ideanote' and request.method == 'GET' and id > 0:
        brainstorm = BrainStorm.objects.get(pk=id)
        context['brainstorm'] = brainstorm  
        blank_ideanote = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance'],title__exact='',description__exact='')
        ideanote = None
        if blank_ideanote.count() == 0:
            ideanote = IdeaNote.objects.create(belongs_to_brainstorm=brainstorm,created_by=global_context['profile_instance'],title='',description='')
        else:
            ideanote = blank_ideanote[0]
        print('********',ideanote)
        context['new_ideanote'] = ideanote
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance']).exclude(title__exact='',description__exact='')
    elif action == 'update_ideanote' and request.method == 'POST':
       
        title = request.POST['title'] if 'title' in request.POST else ''
        description = request.POST['cnt'] if 'cnt' in request.POST else ''
     
        ideanote = IdeaNote.objects.get(pk=id)
        if len(title.strip()) == 0 and len(description.strip()) == 0:
            print('Nothing to update')
            return HttpResponse()
        elif title and len(title.strip())>0:

eunoiaproject/eunoiaapp/templates/eunoiaapp/brainstorm.html
{% extends 'eunoiaapp/base.html' %}
{% block content %}
{% load static %}
<div class="container" id="getting-started">

    <ul class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'eunoiaapp:home'%}">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'eunoiaapp:brainstorm' action='all' id=0 %}">Topics</a>
        </li>
        <li class="breadcrumb-item">
            <a class="" href="{% url 'eunoiaapp:brainstorm' action='new_brainstorm' id=0 %}">+</a>
        </li>
    </ul>

    <!-- Show New Idea Form -->
    {% if action == 'new_brainstorm' or action == 'existing_brainstorm' or action == 'all'%}
    <div class="container">
        <form method="POST" class="form-horizontal" action="{% url 'eunoiaapp:brainstorm' action=action id=0 %}">
            {% include 'eunoiaapp/form.html' %}
        </form>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Topic</th>
                <th>Author</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            {% for brainstorm in brainstorms %}
            <tr class="active">
                <td><a
                        href="{% url 'eunoiaapp:brainstorm' action='ideanote' id=brainstorm.id %}">{{brainstorm.topic}}</a>
                </td>
                <td>{{username}}</td>
                <td>{{brainstorm.created_on}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    {% elif action == 'ideanote' or action == 'new_ideanote' %}
        {% include 'eunoiaapp/brainstormnotes.html' %}
    {% endif %}









</div>


</div>






{% endblock %}

eunoiaproject/eunoiaapp/templates/eunoiaapp/brainstormnotes.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'postitnotes/postit.css' %}">
<link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>


<div class="container" id="getting-started">
  <h1>{{brainstorm.topic}} <a href="{% url 'eunoiaapp:idea' action="new_ideafrombrainstorming" id=brainstorm.id %}" class="btn" id="add_new1">Ideate</a><a href="{% url 'eunoiaapp:brainstorm' action="new_ideanote" id=brainstorm.id %}" class="btn" id="add_new1">+</a></h1>

  <div id="notetemp" style="display: none;">
    <div class="note">
      <a  class="button sticky_btns" title="Fav">💛</a>
      <a  class="button sticky_btns" title="I like it">👍<span class="badge"
          data-badge="8"></span></a>
      <a  class="button sticky_btns" title="Our Strength">💪</a>
      <a  class="button sticky_btns " title="Market Need">🎯</a>
      <a  class="button sticky_btns " title="Research">🔍</a>
      <a  class="button remove">X</a>
      <div class="note_cnt">
        <textarea class="title" placeholder="Enter note title"></textarea>
        <textarea class="cnt" placeholder="Enter note description here"></textarea>
      </div>
    </div>
  </div>
  <div id="board">

    {% if action == 'new_ideanote' %}
   
    <div class="note">
      <a  class="button sticky_btns" title="Fav"    ic-post-to={% url 'eunoiaapp:brainstorm' action='fav_ideanote' id=new_ideanote.id %}  >{%if ideanote.is_fav%}❤️{%else%}💛{%endif%}</a>
      <a  class="button sticky_btns" title="I like it"    ic-post-to={% url 'eunoiaapp:brainstorm' action='like_ideanote' id=new_ideanote.id %}  >👍<span class="badge" data-badge=" {{new_ideanote.all_counts.like_count}}"></span></a>
      <a  class="button sticky_btns" title="Our Strength"    ic-post-to={% url 'eunoiaapp:brainstorm' action='strength_ideanote' id=new_ideanote.id %}  >💪<span class="badge" data-badge=" {{new_ideanote.all_counts.strength_count}}"></span></a>
      <a  class="button sticky_btns " title="Market Need"    ic-post-to={% url 'eunoiaapp:brainstorm' action='marketneed_ideanote' id=new_ideanote.id %}  >🎯<span class="badge" data-badge=" {{new_ideanote.all_counts.marketneed_count}}"></span></a>
      <a  class="button remove">X</a>
    
      <a  class="button remove">X</a>
      <div class="note_cnt">
        <textarea name="title" class="title" placeholder="Enter note title" charswidth="30"   ic-post-to={% url 'eunoiaapp:brainstorm' action='update_ideanote' id=new_ideanote.id %}  ic-trigger-on="blur">{{new_ideanote.title}}</textarea>
        <textarea name="cnt" class="cnt" placeholder="Enter note description here"  charswidth="1024" ic-post-to={% url 'eunoiaapp:brainstorm' action='update_ideanote' id=new_ideanote.id %}  ic-trigger-on="blur">{{new_ideanote.description}}</textarea>
       </div>
    </div>
    {% endif %}

    {% for ideanote in ideanotes %}
   
    <div class="note"  style="transform: rotate({{ideanote.rnum}}deg);">
      <a  class="button sticky_btns" title="Fav"    ic-post-to={% url 'eunoiaapp:brainstorm' action='fav_ideanote' id=ideanote.id %}  >{%if ideanote.is_fav%}❤️{%else%}💛{%endif%}</a>
      <a  class="button sticky_btns" title="I like it"    ic-post-to={% url 'eunoiaapp:brainstorm' action='like_ideanote' id=ideanote.id %}  >👍<span class="badge" data-badge=" {{ideanote.all_counts.like_count}}"></span></a>
      <a  class="button sticky_btns" title="Our Strength"    ic-post-to={% url 'eunoiaapp:brainstorm' action='strength_ideanote' id=ideanote.id %}  >💪<span class="badge" data-badge=" {{ideanote.all_counts.strength_count}}"></span></a>
      <a  class="button sticky_btns " title="Market Need"    ic-post-to={% url 'eunoiaapp:brainstorm' action='marketneed_ideanote' id=ideanote.id %}  >🎯<span class="badge" data-badge=" {{ideanote.all_counts.marketneed_count}}"></span></a>
      <a  class="button remove"   ic-post-to={% url 'eunoiaapp:brainstorm' action='delete_ideanote' id=ideanote.id %}>X</a>
      <div class="note_cnt">
        <textarea name="title" class="title" placeholder="Enter note title" charswidth="30"   ic-post-to={% url 'eunoiaapp:brainstorm' action='update_ideanote' id=ideanote.id %}  ic-trigger-on="blur">{{ideanote.title}}</textarea>
        <textarea name="cnt" class="cnt" placeholder="Enter note description here"  charswidth="1024" ic-post-to={% url 'eunoiaapp:brainstorm' action='update_ideanote' id=ideanote.id %}  ic-trigger-on="blur">{{ideanote.description}}</textarea>
      </div>
    </div>

    {% endfor %}
  </div>
</div>


</div>


<script src="{% static 'postitnotes/jquery.min.js' %}"></script>
<script src="{% static 'postitnotes/jquery-ui.min.js' %}"></script>
<script src="{% static 'postitnotes/postit.js' %}"></script>

<script>


  var noteZindex = 1;
  function deleteNote() {
    $(this).parent('.note').hide("puff", { percent: 133 }, 250);
  };
  var noteTemp = $("div#notetemp").html();
  function newNote() {
    $(noteTemp).hide().prependTo("#board").show("fade", 300).draggable().on('dragstart',
      function () {
        $(this).zIndex(++noteZindex);
        var tempid = Date.now() / 1000 | 0;
        $(this).find('textarea.title').attr('ic-target', '#' + tempid);
        $(this).find('span.noteid').attr('id', '#' + tempid);

      });

    $('.remove').click(deleteNote);
    $('textarea').autogrow();

    $('.note');
    return false;
  };



  $(document).ready(function () {

    $("#board").height($(document).height());

    $("#add_new").click(newNote);

    $('.remove').click(deleteNote);
    // newNote();

    $("div#board").children().each(function(){
      $(this).draggable().on('dragstart',
      function () {
        $(this).zIndex(++noteZindex);
        var tempid = Date.now() / 1000 | 0;
        $(this).find('textarea.title').attr('ic-target', '#' + tempid);
        $(this).find('span.noteid').attr('id', '#' + tempid);

      });
    });


    return false;
  });
</script>

eunoiaproject/eunoiaapp/templates/eunoiaapp/form.html
{% csrf_token %}
{% for error in form.non_field_errors %}
<div class="form-group has-errors text-danger small">
    {{error}}
</div>
{% endfor %}
{% for field in form %}
{% if field.field.widget.attrs.input_type == 'text' %}
<div class="form-group {% if field.errors %}has-error{% endif %}">
    <div class="col-3 col-sm-12">
        <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
    </div>
    <div class="col-9 col-sm-12">
        {{ field }}
        {% if field.help_text %}
        <p class="form-input-hint">{{ field.errors|safe }}</p>
        {% endif %}
    </div>
</div>
{% elif field.field.widget.attrs.input_type == 'checkbox' %}
<div class="form-group {% if field.errors %}has-error{% endif %}">
    <div class="col-3 col-sm-12">
        <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
    </div>
    <div class="col-9 col-sm-12">
        <label class="form-checkbox form-inline">
            {{field}}<i class="form-icon"></i>
        </label>

    </div>

    <div class="col-9 col-sm-12">
        {% if field.help_text %}
        <p class="form-input-hint">{{ field.errors|safe }}</p>
        {% endif %}
    </div>
</div>

{% elif field.field.widget.attrs.input_type == 'textarea' %}
<div class="form-group">
    <div class="col-3 col-sm-12">
        <label class="form-label" for="input-example-6">{{field.label}}</label>
    </div>
    <div class="col-9 col-sm-12">
        {{ field }}
    </div>
</div>


{% elif field.field.widget.attrs.input_type == 'radio' %}
<div class="form-group {% if field.errors %}has-error{% endif %}">
    <div class="col-3 col-sm-12">
        <label class="form-label" for="{{field.name}}">{{field.label}}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
    </div>

    <div class="col-9 col-sm-12">
        <!-- For Ideas -->
        {% for choice in form.status %}
        <label class="form-radio form-inline">
            {{choice.tag}} <i class="form-icon"></i>{{ choice.choice_label }}
        </label>

        {% endfor %}


        <!-- For Features -->
        {% for choice in form.priority %}
        <label class="form-radio form-inline">
            {{choice.tag}} <i class="form-icon"></i>{{ choice.choice_label }}
        </label>

        {% endfor %}


      

    </div>


</div>
{% endif %}

{% endfor %}
<div class="form-group">
    <div class="col-11 col-sm-10">
    </div>
    <div class="col-1 col-sm-1">
        <button type="submit" class="btn btn-success input-group-btn">Ok</button>
    </div>
</div>

eunoiaproject/eunoiaapp/templates/eunoiaapp/idea.html
{% extends 'eunoiaapp/base.html' %}
{% block content %}
{% load static %}
<div class="container" id="getting-started">

    <ul class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'eunoiaapp:home'%}">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'eunoiaapp:idea' action='all' id=0 %}">Ideas</a>
        </li>
        <li class="breadcrumb-item">
            <a class="" href="{% url 'eunoiaapp:idea' action='new_idea' id=0 %}">+</a>
        </li>
    </ul>

    <!-- Show New Idea Form -->
    {% if action == 'new_idea' or action == 'existing_idea' or action == 'new_ideafrombrainstorming' %}
    <div class="container">
        <form method="POST" class="form-horizontal" action="{% url 'eunoiaapp:idea' action=action id=idea_id %}">
            {% include 'eunoiaapp/form.html' %}
        </form>
    </div>

    {% endif %}
    <!-- TODO -->
    <!-- <div class="container">
        <div class="columns">
            <div class="column col-12">
                <div class="form-group">
                    <form action="{% url 'eunoiaapp:idea' action='all' id=0 %}">
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="incubating"><i
                                class="form-icon"></i> Incubating
                        </label>
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="productized"><i
                                class="form-icon"></i> Productized
                        </label>
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="attic"><i
                                class="form-icon"></i> Attic
                        </label>
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="all"><i
                                class="form-icon"></i> All
                        </label>
                    </form>
                </div>
            </div>

        </div>
    </div> -->

    {% if action == 'new_ideafrombrainstorming' or action == 'existing_idea'%}
    <h4>Idea Notes</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Created</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for ideanote in ideanotes %}
            <tr class="active">
                <td>
                    <div class="popover popover-right">

                        <span>{{ideanote.title}}</span>
                        <div class="popover-container">
                            <div class="card">
                                <div class="card-body">
                                    {{ideanote.description}}
                                </div>
                            </div>

                        </div>
                    </div>
                </td>


                <td>{{ideanote.created_by}}</td>
                <td>{{ideanote.created_on}}</td>
                <td>👍<span style="position: relative;top: -11px;left: -6px;">{{ideanote.all_counts.like_count}}</span>
                    💪<span
                        style="position: relative;top: -11px;left: -6px;">{{ideanote.all_counts.strength_count}}</span>
                    🎯<span style="position: relative;top: -11px;left: -6px;">
                        {{ideanote.all_counts.marketneed_count}}</span>

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>




    {% endif %}
    <!-- End if for notes table for ideas -->


    <h4>Other Ideas</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Idea Name</th>
                <th>Author</th>
                <th>Created</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for idea in ideas %}
            <tr class="active">
                <td><a
                        href="{% url 'eunoiaapp:idea' action='existing_idea' id=idea.id %}">{{idea.idea_name}}</a>
                </td>
                <td>{{username}}</td>
                <td>{{idea.created_on}}</td>
                <td>{{idea.status}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>





</div>








{% endblock %}