eunoiaproject/coreapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'coreapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),

    # Brainstorm
    path('home/brainstorm/<action>/<int:id>',views.brainstorm, name='brainstorm'),
    # Ideas
    path('home/idea/<action>/<int:id>',views.idea, name='idea'),

    # kanban
    path('home/kanban/<action>/<int:id>',views.kanban, name='kanban'),

    # Product
    path('home/product/<int:product_id>/<submenu>',login_required(views.ProductView.as_view()), name='product'),
    # path('home/product/<int:product_id>/<submenu>/<action>/<int:id>',views.product, name='product'),
  
    # path('home/product_admin',views.product_admin, name='product_admin')

    path('notify/',views.notify, name='notify'),
    path('signup/', views.signup, name='signup'),

    path('signup/account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

eunoiaproject/eunoiaproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eunoiaapp.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

eunoiaproject/coreapp/views.py
import datetime
from random import randint 
import json

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.template.loader import render_to_string


from django.contrib.auth.models import User

from .tokens import account_activation_token
from .models import Profile
from .forms import SignUpForm


from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.db.models import Q

from django.db.models.functions import TruncMonth
from django.db.models.functions import ExtractMonth
from django.db.models import Avg, Count, Min, Sum

# from .models import
from .tokens import account_activation_token
from .models import Profile, Idea, Product, Feature, FeatureSequence, Activity, BrainStorm, IdeaNote,IdeaNoteAction,ActivitySequence
from .forms import IdeaForm, MyRadioForm, FeatureForm, ActivityForm, BrainStormForm, ShortActivityForm,OpportunityForm


def index(request):
    num =   randint(0,15)
    context = {'chaos_num':num}

    return render(request, "coreapp/index.html", context)

@login_required
def home(request):
    # print(request.headers)
    global_context = get_global_menu_context(request.user)
    print(global_context)
    context = {
        'global_context' : global_context
    }
    return render(request, "coreapp/home.html", context)


@login_required
def kanban(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "action" : action,
        "idea_id" : id,
        'global_context' : global_context
    }
    if action == 'all' and request.method == 'GET':
        context['ideas'] = Idea.objects.filter(created_by=global_context['profile_instance'])

    elif action == 'idea_kanban' and request.method == 'GET':
        context['idea'] = Idea.objects.get(pk=id)
        context['todos'] = Activity.objects.filter(related_to_idea=id,status='TODO',created_by=global_context['profile_instance'])
        context['inprogress'] = Activity.objects.filter(related_to_idea=id,status='IN_PROGRESS',created_by=global_context['profile_instance'])
        context['done'] = Activity.objects.filter(related_to_idea=id,status='DONE',created_by=global_context['profile_instance'])

        context['todo_seq'] = ActivitySequence.objects.filter(type='TODO').order_by('order')
        context['inprogress_seq'] = ActivitySequence.objects.filter(type='IN_PROGRESS').order_by('order')
        context['done_seq'] = ActivitySequence.objects.filter(type='DONE').order_by('order')

    elif action == 'idea_add_todo' and request.method == 'GET':
        context['todo_form'] = ShortActivityForm()

    elif action == 'idea_add_todo' and request.method == 'POST':
        form = ShortActivityForm(request.POST)
        if form.is_valid():
            activity_instance = form.save(commit=False)
            activity_instance.created_by = global_context['profile_instance']
            activity_instance.status = 'TODO'
            activity_instance.complexity = 'UNKNOWN'
            activity_instance.related_to_idea = Idea.objects.get(pk=id)
            activity_instance.save()
            print(activity_instance.id)
            ActivitySequence.objects.create(activity_id = activity_instance.id,order=activity_instance.id, type='TODO')
        return redirect('/home/kanban/idea_kanban/{}'.format(id))

  
    elif action == 'edit_activity' and request.method == 'GET':
        context['todo_form'] = ShortActivityForm()
        activity = Activity.objects.get(pk=id)
        id = activity.related_to_idea.id
        context['idea_id'] = id

    elif action == 'edit_activity' and request.method == 'POST':
        pass

    elif action == 'reorder_activity' and request.method == 'POST':
        orders = json.loads(request.POST['order'])
        print(orders)
        for activity_type in orders:
            for activity_arr in activity_type:
                print(activity_arr)

                ActivitySequence.objects.filter(activity_id = activity_arr[0]).update(order=activity_arr[1],type=activity_arr[2])
                activity = Activity.objects.get(pk = activity_arr[0])
                activity.status=activity_arr[2]
                activity.save()
  
    return render(request, "coreapp/kanban.html", context)

@login_required
def idea(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "username": request.user,
        "action" : action,
        "idea_id" : id,
        "radio_form" : MyRadioForm(),
        "global_context" : global_context
    }
    if action == 'all':
        context['ideas'] = Idea.objects.filter(created_by=global_context['profile_instance'])
    elif action == 'new_idea' and request.method == 'POST':
        form = IdeaForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            idea_instance = form.save(commit=False)
            idea_instance.created_by = global_context['profile_instance']
            idea_instance.save()
            return redirect('/home/idea/all/0')
    elif action == 'new_ideafrombrainstorming' and request.method == 'POST':
        form = IdeaForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            idea_instance = form.save(commit=False)
            idea_instance.created_by = global_context['profile_instance']
            idea_instance.brainstorming = BrainStorm.objects.get(pk=id)
            idea_instance.save()
            return redirect('/home/idea/all/0')
    elif action == 'new_idea' and request.method == 'GET' and id <= 0:
        # In case of new
        context['form'] = IdeaForm()     
    # In case of edit
    elif action == 'existing_idea' and request.method == 'GET' and id > 0:
        idea = Idea.objects.get(pk=id)
        context['idea_instance'] = idea
        context['form'] = IdeaForm(instance=idea)
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=idea.brainstorming,created_by=global_context['profile_instance'])
    elif action == 'new_ideafrombrainstorming' and request.method == 'GET' and id >0:
        context['form'] = IdeaForm()    
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance'])
    elif action == 'existing_idea' and request.method == 'POST' and id > 0:
        idea_instance = Idea.objects.get(pk=id)      
        form = IdeaForm(request.POST, instance=idea_instance)
        if form.is_valid():            
            form.save()
            # if productize, create a product out of it
            idea = Idea.objects.get(pk=id)
            if idea.is_productized():
                product = Product(idea = idea, name = idea.idea_name, owner = global_context['profile_instance'] )   
                product.save()       
            return redirect('/home/idea/all/0')
    


  
    return render(request, "coreapp/idea.html", context)


@login_required
def brainstorm(request,action,id):
    global_context = get_global_menu_context(request.user)    
    context = {
        "action" : action,
        "idea_id" : id,
        "global_context" : global_context
    }
    if action == 'all':
        context['brainstorms'] = BrainStorm.objects.filter(created_by=global_context['profile_instance'])
    elif action == 'new_brainstorm' and request.method == 'POST':
        form = BrainStormForm(request.POST)
        print('FOrm ', form.errors)
        if form.is_valid():
            brainstorm_instance = form.save(commit=False)
            brainstorm_instance.created_by = global_context['profile_instance']
            brainstorm_instance.save()
            return redirect('/home/brainstorm/all/0')
    elif action == 'new_brainstorm' and request.method == 'GET' and id <= 0:
        # In case of new
        context['form'] = BrainStormForm()     
    # In case of edit
    elif action == 'ideanote' and request.method == 'GET' and id > 0:
        context['brainstorm'] = BrainStorm.objects.get(pk=id)
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance']).exclude(title__exact='',description__exact='').select_related()
    elif action == 'new_ideanote' and request.method == 'GET' and id > 0:
        brainstorm = BrainStorm.objects.get(pk=id)
        context['brainstorm'] = brainstorm  
        blank_ideanote = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance'],title__exact='',description__exact='')
        ideanote = None
        if blank_ideanote.count() == 0:
            ideanote = IdeaNote.objects.create(belongs_to_brainstorm=brainstorm,created_by=global_context['profile_instance'],title='',description='')
        else:
            ideanote = blank_ideanote[0]
        print('********',ideanote)
        context['new_ideanote'] = ideanote
        context['ideanotes'] = IdeaNote.objects.filter(belongs_to_brainstorm=id,created_by=global_context['profile_instance']).exclude(title__exact='',description__exact='')
    elif action == 'update_ideanote' and request.method == 'POST':
       
        title = request.POST['title'] if 'title' in request.POST else ''
        description = request.POST['cnt'] if 'cnt' in request.POST else ''
     
        ideanote = IdeaNote.objects.get(pk=id)
        if len(title.strip()) == 0 and len(description.strip()) == 0:
            print('Nothing to update')
            return HttpResponse()
        elif title and len(title.strip())>0:

eunoiaproject/coreapp/templates/coreapp/brainstorm.html
{% extends 'coreapp/base.html' %}
{% block content %}
{% load static %}
<div class="container" id="getting-started">

    <ul class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'coreapp:home'%}">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'coreapp:brainstorm' action='all' id=0 %}">Topics</a>
        </li>
        <li class="breadcrumb-item">
            <a class="" href="{% url 'coreapp:brainstorm' action='new_brainstorm' id=0 %}">+</a>
        </li>
    </ul>

    <!-- Show New Idea Form -->
    {% if action == 'new_brainstorm' or action == 'existing_brainstorm' or action == 'all'%}
    <div class="container">
        <form method="POST" class="form-horizontal" action="{% url 'coreapp:brainstorm' action=action id=0 %}">
            {% include 'coreapp/form.html' %}
        </form>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Topic</th>
                <th>Author</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            {% for brainstorm in brainstorms %}
            <tr class="active">
                <td><a
                        href="{% url 'coreapp:brainstorm' action='ideanote' id=brainstorm.id %}">{{brainstorm.topic}}</a>
                </td>
                <td>{{username}}</td>
                <td>{{brainstorm.created_on}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    {% elif action == 'ideanote' or action == 'new_ideanote' %}
        {% include 'coreapp/brainstormnotes.html' %}
    {% endif %}









</div>


</div>






{% endblock %}

eunoiaproject/coreapp/templates/coreapp/home.html
{% extends 'coreapp/base.html' %}
{% block content %}
{% load static %}
<div class="container" id="getting-started">
    <div class="docs-demo columns">
        <div class="column col-6 col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title h5">News : Series A Round</div>
                </div>
                <div class="card-body">
                    <p> <strong>Our Startup</strong> has secured series A round.</p>
                    <p>
                        We were undergoing funding rounds with Arcor VC, we secured our series A round. Expect good
                        things to happen,
                        specially better
                        computers, better coffee machines and better chairs ;) </p>
                    <p>
                </div>
                <div class="card-footer"><a class="btn btn-primary" href="getting-started/installation.html">More</a>
                </div>
            </div>
        </div>
        <div class="column col-6 col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title h5">Me</div>
                </div>
                <div class="card-body">
                    <div class="columns">
                     
                        <div class="column col-6 col-xs-12">
                            Leave balance
                        </div>
                        <div class="column col-6 col-xs-12">
                                <meter class="meter" value="60" min="0" max="100" low="30" high="80"></meter>
                        </div>
                        <div class="column col-6 col-xs-12">
                            Attendance
                        </div>
                        <div class="column col-6 col-xs-12">
                                <meter class="meter" value="20" optimum="90" min="0" max="100" low="30" high="80"></meter>
                        </div>
                    </div>
                    <div class="columns">

                        <div class="column"><label class="form-switch">
                                <input type="checkbox"><i class="form-icon"></i>I'm In
                            </label>
                        </div>
                        <div class="column"><label class="form-switch">
                                <input type="checkbox"><i class="form-icon"></i>WFH
                            </label>
                        </div>
                        <div class="column"><label class="form-switch">
                            <input type="checkbox"><i class="form-icon"></i>PTO
                        </label>
                    </div>


                    </div>
                    <div class="columns">
                        <div class="column">
                            <a href="#">Set Reminder</a>
                        </div>
                        <div class="column">
                            <a href="#">Set Meeting</a>
                        </div>
                        <div class="column">
                            <a href="#">Find People</a>
                        </div>

                    </div>
                    <div class="columns">

                        <div class="column">
                            <a href="#">Concerns</a>
                        </div>
                        <div class="column">
                            <a href="#">Seek Help</a>
                        </div>
                        <div class="column">
                            <a href="#">Training</a>
                        </div>
                    </div>
                </div>
                <div class="card-footer"><a class="btn btn-primary" href="getting-started/custom.html">More</a>
                </div>
            </div>
        </div>

        <div class="column col-6 col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title h5">Coming Up</div>
                </div>
                <div class="card-body">
                    <div class="chip">
                        <img src="{% static 'spectre/docs/img/avatar-1.png' %}" class="avatar avatar-sm">
                        Cynthia B'day<span><small>(2:30PM Cafetaria)</small></span>
                    </div>
                    <div class="chip">
                        <img src="{% static 'spectre/docs/img/avatar-2.png' %}" class="avatar avatar-sm">
                        Client Visit<span><small>(4:00PM Main Hall)</small></span>
                    </div>

                </div>
                <div class="card-footer"><a class="btn btn-primary" href="getting-started/browsers.html">More</a></div>
            </div>
        </div>
        <div class="column col-6 col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title h5">Welcome New Hires !</div>
                </div>
                <div class="card-body">
                    <figure class="avatar avatar-xl">
                        <img src="{% static 'spectre/docs/img/avatar-3.png' %}" alt="...">
                    </figure>
                    Clara joins as in our design team, she is BA in Design from NYU, she has 6 years of experience.
                    Apart from work whe enjoys yoga, sushi and photography
                </div>
                <div class="card-footer"><a class="btn btn-primary" href="getting-started/whatsnew.html">More</a></div>
            </div>
        </div>

    </div>


</div>
{% endblock %}

eunoiaproject/coreapp/templates/coreapp/idea.html
{% extends 'coreapp/base.html' %}
{% block content %}
{% load static %}
<div class="container" id="getting-started">

    <ul class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'coreapp:home'%}">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'coreapp:idea' action='all' id=0 %}">Ideas</a>
        </li>
        <li class="breadcrumb-item">
            <a class="" href="{% url 'coreapp:idea' action='new_idea' id=0 %}">+</a>
        </li>
    </ul>

    <!-- Show New Idea Form -->
    {% if action == 'new_idea' or action == 'existing_idea' or action == 'new_ideafrombrainstorming' %}
    <div class="container">
        <form method="POST" class="form-horizontal" action="{% url 'coreapp:idea' action=action id=idea_id %}">
            {% include 'coreapp/form.html' %}
        </form>
    </div>

    {% endif %}
    <!-- TODO -->
    <!-- <div class="container">
        <div class="columns">
            <div class="column col-12">
                <div class="form-group">
                    <form action="{% url 'coreapp:idea' action='all' id=0 %}">
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="incubating"><i
                                class="form-icon"></i> Incubating
                        </label>
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="productized"><i
                                class="form-icon"></i> Productized
                        </label>
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="attic"><i
                                class="form-icon"></i> Attic
                        </label>
                        <label class="form-radio form-inline">
                            <input onchange='this.form.submit();' type="radio" name="filter" value="all"><i
                                class="form-icon"></i> All
                        </label>
                    </form>
                </div>
            </div>

        </div>
    </div> -->

    {% if action == 'new_ideafrombrainstorming' or action == 'existing_idea'%}
    <h4>Idea Notes</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Created</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for ideanote in ideanotes %}
            <tr class="active">
                <td>
                    <div class="popover popover-right">

                        <span>{{ideanote.title}}</span>
                        <div class="popover-container">
                            <div class="card">
                                <div class="card-body">
                                    {{ideanote.description}}
                                </div>
                            </div>

                        </div>
                    </div>
                </td>


                <td>{{ideanote.created_by}}</td>
                <td>{{ideanote.created_on}}</td>
                <td>👍<span style="position: relative;top: -11px;left: -6px;">{{ideanote.all_counts.like_count}}</span>
                    💪<span
                        style="position: relative;top: -11px;left: -6px;">{{ideanote.all_counts.strength_count}}</span>
                    🎯<span style="position: relative;top: -11px;left: -6px;">
                        {{ideanote.all_counts.marketneed_count}}</span>

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>




    {% endif %}
    <!-- End if for notes table for ideas -->


    <h4>Other Ideas</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Idea Name</th>
                <th>Author</th>
                <th>Created</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for idea in ideas %}
            <tr class="active">
                <td><a
                        href="{% url 'coreapp:idea' action='existing_idea' id=idea.id %}">{{idea.idea_name}}</a>
                </td>
                <td>{{username}}</td>
                <td>{{idea.created_on}}</td>
                <td>{{idea.status}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>





</div>








{% endblock %}